import type { Answer } from "./model";

export const demoAnswerKeys: Record<string, { correctAnswer: Answer; explanation: string }> = {
  "cat-s1-q1": { correctAnswer: "C", explanation: "20% of 250 = 0.20 × 250 = 50." },
  "cat-s1-q2": { correctAnswer: "C", explanation: "The larger share is 5/8 × 800 = ₹500." },
  "cat-s2-q1": { correctAnswer: "C", explanation: "The terms are n(n + 1): 1×2, 2×3, …, so next is 6×7 = 42." },
  "cat-s2-q2": { correctAnswer: "A", explanation: "Move each letter forward by one: D→E, O→P, G→H." },
  "cat-s3-q1": { correctAnswer: "B", explanation: "(40 + 50 + 60) ÷ 3 = 50 units." },
  "cat-s3-q2": { correctAnswer: "B", explanation: "Increase is 20 on a base of 80: (20/80) × 100 = 25%." },
  "cat-s4-q1": { correctAnswer: "B", explanation: "Prudent means acting with care and good judgment; wise is closest." },
  "cat-s4-q2": { correctAnswer: "B", explanation: "“Neither” is singular here, so it takes the singular verb “is”." },
  "cmat-s1-q1": { correctAnswer: "C", explanation: "Discount = 15% of 1,000 = ₹150, so the price is ₹850." },
  "cmat-s1-q2": { correctAnswer: "B", explanation: "(12 + 18 + 24) ÷ 3 = 18." },
  "cmat-s2-q1": { correctAnswer: "C", explanation: "The terms are n(n + 1): 1×2, 2×3, …, so next is 6×7 = 42." },
  "cmat-s2-q2": { correctAnswer: "A", explanation: "Move each letter forward by one: D→E, O→P, G→H." },
  "cmat-s3-q1": { correctAnswer: "B", explanation: "Abundant means plentiful; its opposite is scarce." },
  "cmat-s3-q2": { correctAnswer: "C", explanation: "The time marker “yesterday” calls for the simple past: submitted." },
  "cmat-s4-q1": { correctAnswer: "C", explanation: "The Reserve Bank of India is the country's central bank." },
  "cmat-s4-q2": { correctAnswer: "A", explanation: "GDP measures the value of final goods and services produced within a country." },
  "cmat-s5-q1": { correctAnswer: "B", explanation: "An MVP contains enough to validate a product idea with early users." },
  "cmat-s5-q2": { correctAnswer: "A", explanation: "A pilot tests actual customer behavior and willingness to pay." },
  "mat-s1-q1": { correctAnswer: "B", explanation: "Abundant means plentiful; its opposite is scarce." },
  "mat-s1-q2": { correctAnswer: "C", explanation: "The time marker “yesterday” calls for the simple past: submitted." },
  "mat-s2-q1": { correctAnswer: "C", explanation: "All the others are perfect squares; 48 is not." },
  "mat-s2-q2": { correctAnswer: "C", explanation: "This is directly given in the first premise." },
  "mat-s3-q1": { correctAnswer: "C", explanation: "Subtract 5 and divide by 3: x = 15/3 = 5." },
  "mat-s3-q2": { correctAnswer: "C", explanation: "Speed = distance ÷ time = 150 ÷ 3 = 50 km/h." },
  "mat-s4-q1": { correctAnswer: "B", explanation: "The increase is 30; 30 ÷ 120 × 100 = 25%." },
  "mat-s4-q2": { correctAnswer: "B", explanation: "Five parts equal 45, so each part is 9; the smaller value is 2×9 = 18." },
  "mat-s5-q1": { correctAnswer: "A", explanation: "Inflation is a sustained increase in the general price level." },
  "mat-s5-q2": { correctAnswer: "B", explanation: "Taxation and public spending are fiscal policy tools." },
  "xat-s1-q1": { correctAnswer: "A", explanation: "Concise means expressing something clearly in few words." },
  "xat-s1-q2": { correctAnswer: "B", explanation: "Applying the first statement to Mira gives the conclusion." },
  "xat-s2-q1": { correctAnswer: "B", explanation: "A responsible decision prioritizes safety, gathers facts and escalates the risk." },
  "xat-s2-q2": { correctAnswer: "B", explanation: "Transparent criteria and evidence help make a fair, reasoned decision." },
  "xat-s3-q1": { correctAnswer: "B", explanation: "The increase is 30 on a base of 120, which is 25%." },
  "xat-s3-q2": { correctAnswer: "B", explanation: "(5 + 10 + 15 + 20) ÷ 4 = 12.5." },
  "xat-s4-q1": { correctAnswer: "B", explanation: "The WTO is headquartered in Geneva, Switzerland." },
  "xat-s4-q2": { correctAnswer: "A", explanation: "The International Monetary Fund publishes the World Economic Outlook." },
};
